name: Comment on issues and PRs when labelled
on:
  issues:
    types: [labeled]
  pull_request_target:
    types: [labeled]

env:
  STALE_MESSAGE: >
    This issue/PR was marked as stalled, it will be automatically closed in 30 days.
    If it should remain open, please leave a comment explaining why it should remain open.
  FAST_TRACK_MESSAGE: Fast-track has been requested by @${{ github.actor }}. Please 👍 to approve.

jobs:
  staleComment:
    if: github.event.label.name == 'stalled'
    runs-on: ubuntu-latest
    steps:
      - name: Post stalled comment
        env:
          COMMENTS_URL: ${{ github.event.issue.comments_url || github.event.pull_request.comments_url }}
        run: |
          curl -X POST $COMMENTS_URL \
          -H "Content-Type: application/json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          --data '{ "body": "$STALE_MESSAGE" }'

  fastTrack:
    if: github.event_name == 'pull_request_target' && github.event.label.name == 'fast-track'
    runs-on: ubuntu-latest
    steps:
      - name: Request Fast-Track
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr comment ${{ github.event.pull_request.number }} --repo ${{ github.repository }} --body "$FAST_TRACK_MESSAGE"
